name = "backend2"
main = "src/index.ts"
compatibility_date = "2025-01-12"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWY2ZmE4ZjEtNTg0ZC00NTc0LTkzNzQtYjMwNmM3NGQ5MjVhIiwidGVuYW50X2lkIjoiNDdhNTY2OGM2NGU3MGI0NzgzMjk2ODQ4YmYwZWYyODQ0OWMzMjUxY2MyMGE5M2U4YzRmMjBhNjIxZGQyYWYwZCIsImludGVybmFsX3NlY3JldCI6IjA3N2U4Y2Q3LWUzOTctNGY2NS1hMjc4LWNhOWY1NDI3ODhjMCJ9.KI2xcXQTeFLBib-6LPj0LprZ5QoQ-HmAhV-bFVRjC6s"
JWT_SECRET="akashYouare"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
